# Generated by Django 5.2.3 on 2025-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(max_length=500, unique=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('origin', models.URLField(max_length=500)),
                ('fallback_urls', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Image URL',
                'verbose_name_plural': 'Image URLs',
                'ordering': ['-id'],
            },
        ),
    ]
