services:
  web:
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS="*"
      - DJANGO_SETTINGS_MODULE=pinterest_feed.settings_prod
      - ACCOUNT=${ACCOUNT}
      - PASSWORD=${PASSWORD}
    volumes:
      - sqlite_data:/app/db
      - static_volume:/app/staticfiles
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

volumes:
  sqlite_data:
  static_volume:

networks:
  app-network:
    driver: bridge
