services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS="*"
      - DJANGO_SETTINGS_MODULE=pinterest_feed.settings_prod
      - ACCOUNT=${ACCOUNT}
      - PASSWORD=${PASSWORD}
    volumes:
      - sqlite_data:/app/db
      - static_volume:/app/staticfiles
      - ./staticfiles:/app/staticfiles  # Mount static files to host path
    restart: unless-stopped

volumes:
  sqlite_data:
  static_volume:
