name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /app/pinterest_feed
          
          # Pull latest changes
          git pull origin master
          
          # Stop existing containers
          docker-compose -f docker-compose.prod.yml down
          
          # Build and start containers
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Run migrations
          docker-compose -f docker-compose.prod.yml exec -T web python manage.py migrate
          
          # Collect static files
          docker-compose -f docker-compose.prod.yml exec -T web python manage.py collectstatic --noinput
          
          # Restart services
          docker-compose -f docker-compose.prod.yml restart
